import type { Move as SplendorMove, PlayerIdentity as SplendorPlayerIdentity } from '@games/splendor';

export const splendorRecordedPlayers = [
  { id: 'dev-alice', displayName: 'Alice Quartz' },
  { id: 'dev-bob', displayName: 'Bob Onyx' },
  { id: 'dev-carmen', displayName: 'Carmen Topaz' },
] as const satisfies readonly SplendorPlayerIdentity[];

export const splendorRecordedConfig = {
  seatCount: 3,
  targetScore: 15,
} as const;

export const splendorPrimaryScenario = {
  setupSeed: 'storybook-primary:setup',
  moves: [
    { type: 'reserve-visible', cardId: 't2-black-04' },
    { type: 'reserve-visible', cardId: 't1-blue-01' },
    { type: 'reserve-visible', cardId: 't3-black-04' },
    { type: 'reserve-visible', cardId: 't2-black-02' },
    { type: 'reserve-visible', cardId: 't3-blue-02' },
    { type: 'reserve-visible', cardId: 't3-blue-04' },
    { type: 'reserve-visible', cardId: 't3-green-02' },
    { type: 'reserve-visible', cardId: 't2-black-01' },
    { type: 'reserve-visible', cardId: 't2-white-03' },
    { type: 'take-distinct', colors: ['white', 'green', 'red'] },
    { type: 'take-distinct', colors: ['white', 'red', 'black'] },
    { type: 'take-distinct', colors: ['blue'] },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-05',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 0, black: 0 }, gold: 2 },
    },
    {
      type: 'purchase-reserved',
      cardId: 't1-blue-01',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 1, black: 1 }, gold: 1 },
    },
    { type: 'take-distinct', colors: ['blue', 'green'] },
    { type: 'take-distinct', colors: ['white', 'red'] },
    { type: 'reserve-visible', cardId: 't2-white-01' },
    { type: 'take-distinct', colors: ['red', 'black'] },
    { type: 'take-distinct', colors: ['green', 'red', 'black'] },
    { type: 'take-distinct', colors: ['green', 'red', 'black'] },
    {
      type: 'purchase-visible',
      cardId: 't1-green-01',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 1, black: 1 }, gold: 1 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-05',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 2, black: 1 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-green-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 1 }, gold: 2 },
    },
    { type: 'take-distinct', colors: ['blue', 'red'] },
    { type: 'take-distinct', colors: ['white'] },
    { type: 'take-distinct', colors: ['blue', 'black'] },
    { type: 'take-distinct', colors: ['red', 'black'] },
    { type: 'take-distinct', colors: ['white', 'green'] },
    { type: 'take-distinct', colors: ['blue', 'black'] },
    { type: 'take-distinct', colors: ['red', 'black'] },
    {
      type: 'purchase-visible',
      cardId: 't1-black-07',
      payment: { tokens: { white: 0, blue: 0, green: 3, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['white', 'green'] },
    {
      type: 'purchase-visible',
      cardId: 't1-black-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 3, black: 1 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['white', 'blue', 'green'] },
    { type: 'take-distinct', colors: ['green', 'red'] },
    { type: 'take-distinct', colors: ['red', 'black'] },
    {
      type: 'purchase-visible',
      cardId: 't1-black-02',
      payment: { tokens: { white: 0, blue: 1, green: 1, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-08',
      payment: { tokens: { white: 0, blue: 0, green: 3, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-07',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 2 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['green', 'red'] },
    {
      type: 'purchase-visible',
      cardId: 't1-red-02',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 0, black: 1 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-03',
      payment: { tokens: { white: 0, blue: 1, green: 1, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-08',
      payment: { tokens: { white: 3, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 1 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-green-03',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-05',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['blue', 'red', 'black'] },
    { type: 'take-distinct', colors: ['blue', 'green'] },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-08',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-black-03',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-03',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['blue', 'green'] },
    { type: 'take-distinct', colors: ['blue'] },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-03',
      payment: { tokens: { white: 0, blue: 0, green: 1, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-green-04',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['blue', 'black'] },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['white', 'green', 'black'] },
    {
      type: 'purchase-visible',
      cardId: 't1-green-05',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-red-03',
      payment: { tokens: { white: 0, blue: 1, green: 1, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-06',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-06',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-07',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-green-06',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-black-06',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['blue', 'green', 'red'] },
    {
      type: 'purchase-visible',
      cardId: 't2-green-05',
      payment: { tokens: { white: 0, blue: 0, green: 2, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-blue-05',
      payment: { tokens: { white: 0, blue: 3, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-blue-01',
      payment: { tokens: { white: 0, blue: 0, green: 1, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 1 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-06',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'claim-noble', nobleId: 'noble-10' },
    {
      type: 'purchase-visible',
      cardId: 't1-black-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-blue-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-green-07',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-black-05',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-07',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-black-08',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-red-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 2 }, gold: 0 },
    },
    { type: 'take-distinct', colors: ['blue', 'green'] },
    {
      type: 'purchase-reserved',
      cardId: 't2-white-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'claim-noble', nobleId: 'noble-5' },
    { type: 'take-distinct', colors: ['blue', 'red'] },
    {
      type: 'purchase-visible',
      cardId: 't2-green-04',
      payment: { tokens: { white: 0, blue: 1, green: 1, red: 0, black: 0 }, gold: 0 },
    },
    { type: 'claim-noble', nobleId: 'noble-8' },
    {
      type: 'purchase-reserved',
      cardId: 't2-black-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-green-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-white-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-blue-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-red-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-reserved',
      cardId: 't2-black-02',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-black-03',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-red-01',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't2-white-04',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 1, black: 0 }, gold: 0 },
    },
    { type: 'claim-noble', nobleId: 'noble-1' },
    {
      type: 'purchase-visible',
      cardId: 't1-green-08',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
    {
      type: 'purchase-reserved',
      cardId: 't2-white-03',
      payment: { tokens: { white: 0, blue: 0, green: 0, red: 0, black: 0 }, gold: 0 },
    },
  ] as const satisfies readonly SplendorMove[],
  checkpoints: {
    opening: 0,
    midgame: 40,
    replayBefore: 40,
    replayAfter: 41,
    nobleChoice: 87,
    finished: 100,
  },
} as const;

export const splendorDiscardScenario = {
  setupSeed: 'discard-seed-5:setup',
  moves: [
    { type: 'reserve-visible', cardId: 't3-blue-01' },
    { type: 'reserve-visible', cardId: 't2-green-03' },
    { type: 'reserve-visible', cardId: 't1-blue-08' },
    { type: 'reserve-visible', cardId: 't3-blue-04' },
    { type: 'reserve-visible', cardId: 't3-blue-02' },
    { type: 'reserve-visible', cardId: 't2-red-05' },
    { type: 'reserve-visible', cardId: 't2-black-02' },
    { type: 'reserve-visible', cardId: 't2-black-05' },
    { type: 'reserve-visible', cardId: 't3-blue-03' },
    { type: 'take-distinct', colors: ['red'] },
    { type: 'take-distinct', colors: ['red'] },
    { type: 'take-distinct', colors: ['blue', 'green', 'red'] },
    { type: 'take-distinct', colors: ['white', 'red'] },
    { type: 'take-distinct', colors: ['white', 'blue', 'red'] },
    {
      type: 'purchase-visible',
      cardId: 't1-black-01',
      payment: { tokens: { white: 0, blue: 1, green: 1, red: 1, black: 0 }, gold: 1 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-red-06',
      payment: { tokens: { white: 1, blue: 0, green: 0, red: 2, black: 0 }, gold: 1 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-01',
      payment: { tokens: { white: 0, blue: 1, green: 0, red: 1, black: 0 }, gold: 2 },
    },
    { type: 'take-distinct', colors: ['white', 'red', 'black'] },
    { type: 'take-distinct', colors: ['blue', 'red'] },
    { type: 'take-distinct', colors: ['blue'] },
    { type: 'take-distinct', colors: ['green'] },
    { type: 'take-distinct', colors: ['green'] },
    { type: 'take-distinct', colors: ['green', 'red', 'black'] },
    { type: 'take-distinct', colors: ['blue'] },
    { type: 'take-distinct', colors: ['white', 'blue', 'black'] },
    { type: 'take-distinct', colors: ['white', 'red'] },
    {
      type: 'purchase-visible',
      cardId: 't1-green-02',
      payment: { tokens: { white: 1, blue: 1, green: 0, red: 1, black: 1 }, gold: 0 },
    },
    {
      type: 'purchase-visible',
      cardId: 't1-white-03',
      payment: { tokens: { white: 0, blue: 2, green: 1, red: 0, black: 1 }, gold: 1 },
    },
    { type: 'take-distinct', colors: ['white', 'red', 'black'] },
  ] as const satisfies readonly SplendorMove[],
  checkpoints: {
    discard: 29,
  },
} as const;
